import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#835000',
        'primary-dim': '#724600',
        'primary-container': '#fca21e',
        'primary-fixed': '#fca21e',
        'primary-fixed-dim': '#ec9508',
        'on-primary': '#fff0e4',
        'on-primary-fixed': '#2e1900',
        'on-primary-container': '#4d2e00',
        'on-primary-fixed-variant': '#593500',
        secondary: '#515d69',
        'secondary-dim': '#46515d',
        'secondary-container': '#d8e4f3',
        'secondary-fixed': '#d8e4f3',
        'secondary-fixed-dim': '#cad5e4',
        'on-secondary': '#ebf3ff',
        'on-secondary-fixed': '#35404c',
        'on-secondary-fixed-variant': '#515d69',
        'on-secondary-container': '#48535f',
        tertiary: '#6c5a00',
        'tertiary-dim': '#5e4e00',
        'tertiary-container': '#ffd709',
        'tertiary-fixed': '#ffd709',
        'tertiary-fixed-dim': '#efc900',
        'on-tertiary': '#fff2cd',
        'on-tertiary-fixed': '#453900',
        'on-tertiary-fixed-variant': '#665500',
        'on-tertiary-container': '#5b4b00',
        surface: '#f6f6f6',
        'surface-dim': '#d2d5d5',
        'surface-bright': '#f6f6f6',
        'surface-variant': '#dbdddd',
        'surface-tint': '#835000',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f1f1',
        'surface-container': '#e7e8e8',
        'surface-container-high': '#e1e3e3',
        'surface-container-highest': '#dbdddd',
        'on-surface': '#2d2f2f',
        'on-surface-variant': '#5a5c5c',
        'on-background': '#2d2f2f',
        background: '#f6f6f6',
        outline: '#757777',
        'outline-variant': '#acadad',
        error: '#b02500',
        'error-dim': '#b92902',
        'error-container': '#f95630',
        'on-error': '#ffefec',
        'on-error-container': '#520c00',
        'inverse-surface': '#0c0f0f',
        'inverse-on-surface': '#9c9d9d',
        'inverse-primary': '#fca21e',
      },
      fontFamily: {
        sans: ['Manrope', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      boxShadow: {
        ambient: '0 32px 64px -12px rgba(81,93,105,0.04)',
        float: '0 8px 32px rgba(81,93,105,0.04)',
        card: '0 4px 20px -4px rgba(81,93,105,0.04)',
      },
      keyframes: {
        'pulse-red': {
          '0%, 100%': { transform: 'scale(0.95)', boxShadow: '0 0 0 0 rgba(249,86,48,0.7)' },
          '70%': { transform: 'scale(1)', boxShadow: '0 0 0 10px rgba(249,86,48,0)' },
        },
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(12px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
      },
      animation: {
        'pulse-red': 'pulse-red 2s infinite',
        'fade-up': 'fade-up 0.4s ease-out both',
        'fade-in': 'fade-in 0.3s ease-out both',
      },
    },
  },
  plugins: [],
}

export default config
